name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test
    - name: Build
      run: yarn build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      run: |
        scp -r ./build root@121.41.170.32:/kb/ending-project
        ssh root@121.41.170.32 "docker restart ending-project"

